//This file is the stocking data

DG.stock = {
  monsterTags: [
    'adventurer',
    'animal',
    'animated',
    'chaos',
    'cleanup',
    'cult', 
    'demon', 
    'devil',
    'dragon',
    'elemental',
    'familiar', 
    'flying',
    'giant',
    'goblin',
    'huge',
    'human',
    'humanoid',
    'insect',
    'large',
    'law', 
    'lycanthrope',
    'mammal', 
    'ogre',
    'overlord', 
    'reptile',
    'spider', 
    'stealthy',
    'undead',  
    'underdark',
    'vermin',
    'weird'],
		
  allAttitudes: [
  'surly',
  'fearful',
  'scared',
  'angry',
  'bruised',
  'irritated',
  'irritable',
  'lazy',
  'sleeping',
  'sleepy',
  'tired',
  'ragged',
  'imprisoned',
  'distracted',
  'reluctant',
  'obnoxious',
  'insane',
  'vicious',
  'friendly',
  'approachable',
  'duplicitous',
  'curious',
  'alert',
  'libidinous',
  'tough',
  'wounded',
  'sick',
  'dullwitted',
  'vituperative',
  'whimsical',
  'mean',
  'aggressive',
  'hungry',
  'famished',
  'starving',
  'sleep-deprived',
  'stunned',
  'ensorcelled',
  'crazed',
  'calm',
  'apathetic',
  'accusatory',
  'awed',
  'bitter',
  'cynical',
  'vengeful',
  'condescending',
  'callous',
  'contemplative',
  'hot-tempered',
  'contemptuous',
  'scornful',
  'derisive',
  'erudite',
  'forthright',
  'frank',
  'gloomy',
  'haughty',
  'indignant',
  'familiar',
  'judgemental',
  'jovial',
  'morose',
  'malicious',
  'cheerful',
  'obsequious',
  'patronizing',
  'possessed',
  'pessimistic',
  'eccentiric',
  'ribald',
  'reverent',
  'bantering',
  'invisible',
  'reflective',
  'sarcastic',
  'sincere',
  'solemn',
  'crass',
  'vacuous',
  'presumptuous',
  'subversive',
  'capricious',
  'wary',
  'reticent',
  'cowardly',
  'moribund',
  'lugubrious',
  'passive',
  'indolent',
  'droll',
  'commanding',
  'reserved',
  'miserable',
  'wizened',
  'spectral',
  'skeletal',
  'languid',
  'dissolute',
  'inquisitive',
  'drunk',
  'heavily armored',
  'stoned',
  'dubious',
  'reasonable',
  'vexed',
  'worried',
  'vigilant',
  'active',
  'cautious',
  'pious',
  'fanatic',
  'trapped',
  'imprisoned',
  'enigmatic',
  'paralyzed',
  'wicked',
  'pathetic',
  'ravenous',
  'hurried',
  'satiated',
  'garrulous',
  'anxious',
  'startled',
  'spooked',
  'infectious',
  'bored',
  'villainous',
  'greedy',
  'cantakerous',
  'phlegmatic',
  'furious',
  'surprised'
  ],
  basicAttitudes: [
  'fearful',
  'scared',
  'angry',
  'irritated',
  'ravenous',
  'lazy',
  'sleeping',
  'sleepy',
  'tired',
  'satiated',
  'curious',
  'alert',
  'tough',
  'infectious',
  'poisonous',
  'wounded',
  'sick',
  'aggressive',
  'hungry',
  'famished',
  'starving',
  'stunned',
  'ensorcelled',
  'calm',
  'wary',
  'moribund',
  'passive',
  'active',
  'cautious',
  'pathetic',
  'spooked',
  'startled',
  'surprised'
  ],
  monsters: [ 
	[
		  { name: "kobold", int: 9, tags: ['dragon','humanoid','chaos','reptile','stealthy']},
		  { name: "goblin", int: 9, tags: ['goblin','humanoid','chaos','stealthy' ]}, 
		  { name: "spider", int: 1, tags: ['vermin','spider','stealthy']},
		  { name: "snake",  int: 3, tags: ['vermin', 'animal', 'reptile','familiar']},
		  { name: "lizard",  int: 3, tags: ['vermin','animal','reptile','familiar']}, 
		  { name: "rat", int: 4, tags: ['vermin', 'mammal', 'animal','familiar']},
		  { name: "giant beetle", int: 1, tags: ['vermin','insect']},
		  { name: "giant rat", int: 4, tags: ['vermin', 'mammal', 'animal']},
		  { name: "bat", int: 4, tags: ['vermin', 'mammal', 'animal','familiar', 'flying']},
		  { name: "centipede", int: 1, tags: ['vermin','insect']},
		  { name: "stirge", int: 1, tags: ['vermin','insect','chaos','weird', 'flying']},
		  { name: "skeleton",  int: 3, tags: ['undead', 'chaos']},
		  { name: "giant tick", int: 1, tags: ['vermin','insect']},
		  { name: "rabid dog", int: 4, tags: ['vermin', 'mammal', 'animal']},
		  { name: "tunnel wolf", plural: "tunnel wolves", int: 6, tags: ['mammal', 'animal', 'goblin', 'stealthy']},
		  { name: "bandit", int: 10, tags: ['chaos', 'human','humanoid']},
		  { name: "novice adventurer", int: 10, tags: ['adventurer', 'law', 'human', 'humanoid']},
		  { name: "weekend cultist", int: 10, tags: ['cult', 'chaos', 'human', 'humanoid']},
		  { name: "underling", int: 10, tags: ['overlord', 'human','humanoid']} 
	  ], //level 1
	  [
		  { name: "zombie",  int: 3, tags: ['undead',  'chaos']},
		  { name: "wererat",  int: 10, tags: ['human', 'lycanthrope', 'stealthy', 'chaos','humanoid']},
		  { name: "spirit",  int: 10, tags: ['undead', 'flying', 'stealthy']},
		  { name: 'vampire bat', int: 4, tags: ['vermin', 'mammal', 'animal', 'flying', 'familiar', 'stealthy']},
		  { name: "ooze", int: 1, tags: ['vermin', 'cleanup', 'stealthy']},
		  { name: "orc", int: 10, tags: ['goblin', 'humanoid', 'chaos' ]}, 
		  { name: "jelly", plural: 'jellies', int: 1, tags: ['vermin', 'cleanup']},
		  { name: "shadow",  int: 6, tags: ['undead',  'chaos', 'stealthy']},
		  { name: "dark elf", plural: 'dark elves', int: 12, tags: ['chaos', 'humanoid', 'stealthy']},
		  { name: "mutant", int: 10, tags: ['human','weird','chaos']},
		  { name: "crawling hand",  int: 3, tags: ['undead', 'chaos', 'familiar']},
		  { name: "ape man", plural: "ape men", int: 10, tags: ['human', 'weird', 'chaos', 'humanoid', 'stealthy']},
		  { name: "hobgoblin", int: 10, tags: ['goblin', 'chaos', 'humanoid' ]}, 
		  { name: "giant weasel", int: 5, tags: ['mammal', 'animal', 'stealthy']},
		  { name: "big lizard",  int: 3, tags: ['animal', 'reptile']},
          { name: "beast man", plural: 'beast men',  int: 10, tags: ['humanoid', 'weird', 'chaos']},		  
		  { name: "lizard man",  plural: 'lizard men', int: 3, tags: ['humanoid', 'reptile']}, 
		  { name: "berserker", int: 10, tags: ['chaos', 'human', 'humanoid']},
		  { name: "gnoll", int: 10, tags: ['chaos','humanoid' ]}, 
		  { name: "giant ant", int: 3, tags: ['vermin', 'insect']},
		  { name: "adventurer", int: 11, tags: ['adventurer', 'law', 'human', 'humanoid']},
		  { name: "cultist", int: 11, tags: ['cult', 'chaos', 'human', 'humanoid']},
		  { name: "minion", int: 11, tags: ['overlord', 'human', 'humanoid']} 
	  ], //level 2
	  [
		  { name: "ghast",  int: 8, tags: ['undead', 'chaos', 'stealthy']},
          { name: "small elemental", int: 8, tags: ['weird', 'chaos', 'elemental' ]}, 
		  { name: "giant lizard",  int: 3, tags: ['animal', 'reptile', 'large']}, 
		  { name: "bugbear", int: 10, tags: ['goblin', 'chaos', 'humanoid', 'large', 'stealthy' ]}, 
		  { name: "creeper", int: 10, tags: ['weird','chaos','humanoid','stealthy' ]}, 
		  { name: "snake man", plural: "snake men", int: 10, tags: ['humanoid', 'reptile', 'cult', 'stealthy']},
		  { name: "ghoul",  int: 8, tags: ['undead', 'chaos']},
		  { name: "gremlin",  int: 8, tags: ['demon', 'chaos', 'flying', 'weird', 'humanoid']},
		  { name: "carrion crawler", int: 2, tags: ['weird', 'cleanup','large']},
		  { name: "rust monster", int: 3, tags: ['weird', 'cleanup']},
		  { name: "gelatinous cube", int: 2, tags: ['weird', 'cleanup', 'large']},
		  { name: "doppelganger", int: 10, tags: ['weird', 'chaos', 'humanoid' ]}, 
		  { name: "giant spider", int: 1, tags: ['large', 'spider', 'stealthy']},
		  { name: "night lurker",  int: 8, tags: ['weird','humanoid', 'chaos', 'stealthy']},
		  { name: "giant snake", int: 3, tags: ['large', 'animal', 'reptile']},
		  { name: "harpy",  plural: 'harpies', int: 10, tags: ['humanoid', 'weird', 'chaos', 'flying']},
		  { name: "porting hound", int: 10, tags: ['mammal', 'law', 'weird', 'stealthy']},
		  { name: "ogre", int: 9, tags: ['goblin', 'ogre', 'giant', 'chaos', 'humanoid', 'large' ]}, 
		  { name: "slime", int: 1, tags: ['weird', 'stealthy', 'cleanup']},
		  { name: "demonic minion", int: 10, tags: ['weird', 'chaos','demon' ]}, 
		  { name: "devil spawn", plural: "devil spawn", int: 10, tags: ['weird', 'chaos', 'devil' ]}, 
		  { name: "imp", int: 10, tags: ['weird', 'stealthy', 'chaos', 'devil', 'familiar' ]}, 
		  { name: "werewolf", plural: 'werewolves', int: 10, tags: ['human', 'lycanthrope', 'stealthy', 'chaos','humanoid']},
		  { name: "wight", int: 9, tags: ['undead', 'chaos']},
		  { name: "veteran adventurer", int: 12, tags: ['adventurer', 'law', 'human', 'humanoid']},
		  { name: "fanatic cultist", int: 12, tags: ['cult', 'chaos', 'human', 'humanoid']},
		  { name: "evil henchman", plural: "evil henchmen", int: 11, tags: ['overlord', 'human', 'humanoid']} 
	  ], //level 3
	  [ 
		  { name: "lesser demon", int: 11, tags: ['weird','chaos','demon' ]},
          { name: "lesser elemental", int: 9, tags: ['weird','chaos','elemental' ]},           
		  { name: "servant devil", int: 11, tags: ['weird','chaos','devil' ]}, 
		  { name: "cockatrice", int: 5, tags: ['weird','chaos']}, 
		  { name: "serpent priest",  int: 11, tags: ['humanoid','reptile','cult']},
		  { name: "wereboar", int: 11, tags: ['human','lycanthrope','chaos','humanoid','large']},
		  { name: "weretiger", int: 12, tags: ['human','lycanthrope','chaos','humanoid','large']},
		  { name: "owl bear", int: 6, tags: ['mammal', 'animal', 'weird','large']},
		  { name: "boar croc", int: 3, tags: ['animal','reptile','huge']}, 
		  { name: "displacer cat", int: 6, tags: ['mammal', 'animal', 'weird', 'large']},
		  { name: "hell hound", int: 11, tags: ['weird','dog','large','chaos','devil' ]},
		  { name: "night gaunt", int: 11, tags: ['weird', 'flying', 'large', 'chaos' ]},
		  { name: "raptor", int: 3, tags: ['animal','reptile']}, 
		  { name: "minotaur", int: 11, tags: ['weird','humanoid','large']},
		  { name: "roper", int: 11, tags: ['weird','underdark','large']},
		  { name: "crawling horror", int: 11, tags: ['weird','underdark','large','chaos']},
		  { name: "spectre", int: 12, tags: ['undead', 'chaos', 'stealthy', 'flying']},
		  { name: "mold", int: 1, tags: ['weird','cleanup','large','underdark']},
		  { name: "mimic", int: 11, tags: ['weird','chaos']},
		  { name: "troll", int: 11, tags: ['ogre','giant','weird','chaos','large']},
		  { name: "hill giant", int: 10, tags: ['giant','chaos','huge']},
		  { name: "young dragon", int: 11, tags: ['dragon','chaos','flying','large']},
		  { name: "animated statue", int: 5, tags: ['animated','large']},
		  { name: "wraith", int: 10, tags: ['undead','stealthy', 'chaos']},
		  { name: "mummy", plural: "mummies", int: 10, tags: ['undead', 'chaos']},
		  { name: "gargoyle", int: 10, tags: ['elemental', 'animated', 'flying', 'chaos']},
		  { name: "heroic adventurer", int: 13, tags: ['adventurer', 'law', 'human','humanoid']},
		  { name: "insane cultist", int: 13, tags: ['cult', 'chaos', 'human','humanoid']},
		  { name: "villainous lieutenant", int: 12, tags: ['overlord', 'human','humanoid']} 
	  ], // level 4
	  [
		  { name: "medusa",  int: 11, tags: [ 'stone', 'weird', 'chaos']},
		  { name: "robot", int: 11, tags: [ 'animated', 'weird', 'large']},
		  { name: "rakshasa", int: 11, tags: [ 'lycanthrope', 'demon', 'large']},
		  { name: "werebear", int: 12, tags: ['human','lycanthrope','humanoid','huge']},
		  { name: "serpent sorceror",  int: 12, tags: ['humanoid','weird','reptile','cult']},
		  { name: "troll lord", int: 12, tags: ['ogre','giant','weird','chaos','large']},
		  { name: "umber hulk", int: 5, tags: ['weird','chaos','large','underdark' ]},
		  { name: "horror", int: 9, tags: ['weird','chaos','underdark' ]},
		  { name: "manticore", int: 10, tags: ['weird','chaos','underdark' ]},
		  { name: "giant", int: 11, tags: ['giant','chaos','enormous']},
		  { name: "ogre mage", plural: "ogre magi", int: 12, tags: ['ogre', 'large', 'chaos']},
		  { name: "salamander", int: 9, tags: ['weird','chaos','elemental','large' ]},
		  { name: "stalker", int: 11, tags: [ 'weird', 'elemental', 'chaos']},
		  { name: "wyvern", int: 9, tags: ['dragon', 'chaos', 'large', 'flying']},
		  { name: "dinosaur", int: 3, tags: ['reptile', 'huge', 'animal']},
		  { name: "elemental", int: 5, tags: ['weird', 'chaos', 'elemental', 'large' ]},
		  { name: "mental squidman", plural: 'mental squidmen', int: 14, tags: ['weird', 'chaos', 'underdark' ]},
		  { name: "demon", int: 12, tags: ['weird','chaos','demon' ]},
		  { name: "devil", int: 12, tags: ['weird','chaos','devil' ]},
		  { name: "subadult or adult dragon", int: 13, tags: ['dragon','flying','chaos','huge']},
		  { name: "ghost", int: 12, tags: ['undead',  'chaos']},
		  { name: "golem", int: 11, tags: ['animated','huge']},
		  { name: "grizzled adventurer", int: 14, tags: ['adventurer', 'law', 'human','humanoid']},
		  { name: "inner circle cultist", int: 14, tags: ['cult', 'chaos', 'human','humanoid']},
		  { name: "villain", int: 13, tags: ['overlord', 'human', 'humanoid']} 
	  ], //level 5
	  [
		  { name: "hydra", int: 4, tags: ['reptile', 'huge', 'weird']},
		  { name: "demon lord", int: 14, tags: ['weird', 'chaos', 'demon' ]},
		  { name: 'elemental prince', int: 10, tags: ['weird', 'chaos', 'elemental', 'huge' ]},
		  { name: "devil prince", int: 14, tags: ['weird', 'chaos', 'devil' ]},
		  { name: "lich", plural: 'liches', int: 15, tags: ['undead', 'chaos']},
		  { name: "beholder", int: 15, tags: ['chaos', 'weird', 'large', 'underdark']},
		  { name: "wizard", int: 15, tags: [ 'law', 'chaos', 'human', 'humanoid']},
		  { name: "gorgon", int: 5, tags: [ 'huge', 'weird', 'chaos']},
		  { name: "chimera", int: 4, tags: ['reptile', 'dragon', 'flying', 'huge', 'weird']},
		  { name: "basilisk", int: 4, tags: ['reptile', 'huge', 'weird']},
		  { name: "vampire", int: 14, tags: ['undead', 'flying',  'chaos']},
		  { name: "giant worm", int: 12, tags: ['weird','chaos', 'huge','underdark']},
		  { name: "old or very old dragon", int: 12, tags: ['dragon', 'flying', 'chaos', 'huge']},
		  { name: "legendary adventurer", int: 15, tags: ['adventurer', 'law', 'human', 'humanoid']},
		  { name: "cult leader", int: 15, tags: ['cult', 'chaos', 'human', 'humanoid']},
		  { name: "evil overlord", int: 14, tags: ['overlord', 'human', 'humanoid']} 
	  ] //level 6
  ],
  treasure: [{label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
			 {label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
			 {label: "x 10 GP gem", value: 10},
			 {label: "x 10 GP gem", value: 10},
             {label: "x 10 GP gem", value: 10},
			 {label: "x 20 GP gem", value: 20},
			 {label: "x 30 GP gem", value: 30},
			 {label: "x 10 GP gem", value: 10},
			 {label: "x 20 GP gem", value: 20},
			 {label: "x 30 GP gem", value: 30},
			 {label: "x 40 GP gem", value: 40},
			 {label: "x 50 GP gem", value: 50},
			 {label: "x 60 GP gem", value: 60},
			 {label: "x 80 GP gem", value: 80},
             {label: "x 100 GP gem", value: 100},
             {label: "x 200 GP gem", value: 200},
             {label: "x 300 GP gem", value: 300},
             {label: "x 500 GP gem", value: 500},
			 {label: "x 600 GP gem", value: 600},
             {label: "x 800 GP gem", value: 800},
			 {label: "x 10 GP gem", value: 10},
             {label: "x 100 GP gem", value: 100},
             {label: "x 200 GP gem", value: 200},
             {label: "x 300 GP gem", value: 300},
             {label: "x 500 GP gem", value: 500},
			 {label: "x 10 GP gem", value: 10},
             {label: "x 100 GP gem", value: 100},
             {label: "x 200 GP gem", value: 200},
             {label: "x 300 GP gem", value: 300},
			 {label: "x 1000 GP gem", value: 1000},
             {label: "x 1000 GP gem", value: 1500},
             {label: "x 2000 GP gem", value: 2000},
             {label: "Ring", value: "X"},
			 {label: 'Torc', value: "X"},
			 {label: 'Necklace', value: "X"},
			 {label: 'Earrings', value: "X"},
			 {label: 'Earring', value: "X"},
			 {label: 'Anklet', value: "X"},
			 {label: 'Bracelet', value: "X"},
			 {label: 'Jewelled Dagger', value: "X"},
			 {label: 'Jewelled Belt', value: "X"},
			 {label: 'Jewelled Helm', value: "X"},
			 {label: 'Jewelled Cup', value: "X"},
			 {label: 'Jewelled Pin', value: "X"},
			 {label: 'Jewelled Brooch', value: "X"},
			 {label: 'Jewelled Comb', value: "X"},
			 {label: 'Crown', value: "X"},
			 {label: 'Tiara', value: "X"},
			 {label: 'Jewelled Bone', value: "X"},
			 {label: 'Jewelled Book', value: "X"},
			 {label: 'Jewelled Box', value: "X"},
			 {label: 'Statuette', value: "X"},
			 {label: 'Vase', value: "X"},
			 {label: 'Urn', value: "X"},
			 {label: 'Vessel', value: "X"},
			 {label: 'Chalice', value: "X"}
			 			
            ],
  magicItems: [ "Healing potion",
                "Strong healing potion",
                "potion",
                "potion",
                "potion",
                "Scroll of spells",
                "Scroll of warding",
                "scroll",
                "trinket",
                "trinket",
                "wand",
                "ring",
                "sword",
                "staff",
                "armor",
                "weapon",
                "book",
                "miscellaneous" ],
  minorMagicItems: [ "Weak healing potion",
                "Healing potion",
                "potion",
                "potion",
                "potion",
				"Scroll with one spell",
                "Scroll with one spell",
                "Scroll of warding",
                "scroll",
                "trinket" ],
  potions: [ "Giant growth",
             "Shrinking",
			 "Levitation",
			 "Flight",
			 "Fire breath",
			 "Armored skin",
			 "Water breathing",
			 "Restoration",
			 "Cure disease",
			 "Universal antidote",
			 "Antidote to a specific poison",
			 "Delusion",
			 "Lust",
			 "Silence",
			 "Deathlike trance",
			 "Intestinal distress",
			 "Sleeping",
			 "Infatuation",
			 "Polymorph",
			 "Disguise",
			 "Invisibility",
			 "Wall climbing",
			 "Gravity inversion",
			 "Magic suppression",
			 "Inebriation",
			 "Heroism",
			 "Giant strength",
			 "Paranoid Rage",
			 "Animal language",
			 "Speaking any language",
			 "Planar visitation",
			 "Spirit travel",
			 "Treasure finding",
			 "Elemental resistance",
			 "Animal control",
			 "Speed",
			 "Leaping",
			 "Purgation",
			 "Gaseous form",
			 "Weird Mutation",
			 "Spell preparation",
			 "Regeneration"
  ],
  swordPowers: [
    "Sings when swung",
    "Invisible while sheathed",
	"No encumbrance",
	"Indestructible",
	"Burning Flame on a crit",
	"Chilling Cold on a crit",
	"Stunning Lightning on a crit",
	"Lifestealing: 1 HP each hit",
	"Blood magic: drains wielder 1 HP per combat round",
	"Detects traps 33%",
	"Intelligence and Ego",
	"Glows when enemies are close",
	"Shines bright in combat",
	"Talks",
	"+2 damage to favored enemy",
	"Flashing parries: +2 AC",
	'Energy blade',
	'Can change size',
	'Does not rust or tarnish',
	'Spell Blocking: +2 Save vs Magic',
	'Vorpal',
	'Derring Do rolls +2',
	'Locate Objects',
	'Cursed',
	'Flaming',
	'Dancing',
	'Flies to hand',
	'Holy'
  ], 
  swords: ["Great sword",
  "Great sword",
  "Zweihander Flamberge",
  "Claymore",
  "Long sword",
  "Long sword",
  "Long sword",
  "Broadsword",
  "Broadsword",
  "Broadsword",
  "Broadsword",
  "Cutlass",
  "Scimitar",
  "Tulwar",
  "Katana",
  "Short sword",
  "Short sword",
  "Short sword",
  "Small sword",
  "Hanger",			
  "Rapier",
  "Epee",
  "Falchion"],
  staves: [
      "Utility - changes length betwen 3 and 20 feet, can grow ladder rungs and hook at end, +1 weapon, ranged weapon - energy darts (1D6 damage, +1 to hit, range 60')",
	  "Puissance - +50% range, +50% duration, reduce target's save by 2, or add 25% damage to any spell cast by wizard",
      "Three Spells",
	  "Five Spells",
	  "Seven Spells",
	  "Healing", 
	  "Commanding", 
	  "the Snake",
	  "Striking",
	  "Withering",
	  "Power",
	  "Wizardry"],
  scrolls: ["Scroll", "Scroll", "Scroll",
  "Scroll with one arcane spell", 
  "Scroll with one holy spell", 
    "Scroll with one arcane spell", 
  "Scroll with one holy spell", 
    "Scroll with one arcane spell", 
  "Scroll with one holy spell", 
  "Scroll with two arcane spells", 
  "Scroll with two holy spells",
    "Scroll with two arcane spells", 
  "Scroll with two holy spells",
    "Scroll with three arcane spells", 
  "Scroll with three holy spells",
  "Scroll with a trap spell that casts upon reader",
  "Scroll of protection from (some great danger in this dungeon)"],
  books: ["Book", "Libram", "Tome", "Manual", "Grimoire"],
  rings: ["Regeneration", 
	  "Weakness", 
	  "Invisibility", 
	  "Protection", 
	  "Spell Turning",
      "Disguise",
      "Silence",
      "Greater Protection",
      "Cold Resistance",
      "Posion Resistance",
      "Astral Walking",
      "Life Draining",
      "Poison Touch",
      "Influence",
      "Wisdom",	  
	  "Spell Storing", 
	  "Fire Resistance", 
	  "Flying", 
	  "Shooting Stars", 
	  "Telekinesis", 
	  "Delusion", 
	  "Djinn Summoning", 
	  "Three Wishes", 
	  "Contrariness",
	  "Regurgitation",
	  "Absentmindedness"],
  wands: [
      "Spell Range Doubling",
	  "Spell Duration Doubling",
	  "Spell Penetration (-2 to target save vs spell)",
	  "Weapon Rusting",
	  "Hold Portal",
	  "Sleep",
	  "Phantasmal Forces",
	  "Locate Object",
	  "Invisibility",
	  "Wizard Lock",
	  "Detect Evil",
	  "ESP",
	  "Knock",
	  "Continual Light",
	  "Detect Invisible",
	  "Levitate",  
	  "Detect Magic", 
	  "Light",
	  "Charm Person",
	  "Flight",
	  "Dispel Magic",
	  "Infravision",
	  "Slow",
	  "Haste",
	  "Protection from Missiles",
	  "Water Breathing",
	  "Protection from Evil",
	  "Hold Portal",
	  "Secret doors and Traps detection", 
	  "Illusion", 
	  "Fear", 
	  "Cold",
	  "Paralization",
	  "Fire Balls",
	  "Lightning Bolts",
	  "Polymorph",
	  "Negation",
	  "Pass-Wall",
	  "Cloudkill",
	  "Dimension Door"
  ],
  miscellaneous: ["Crystal ball",
  "Crystal Ball with Clairaudience",
  'Crystal Ball with Special Offers',
  'Medallion of ESP',
  'Amulet vs Scrying',
  'Scarab of Projection from Evil High Priests',
  'Bag of Holding',
  'Censor of Air Elementals',
  'Stone of Earth Elementals',
  'Brazier of Fire Elementals',
  'Bowl of Water Elementals',
  'Efreet Bottle',
  'Displacer Cloak',
  'Elven Cloak',
  'Elven Boots',
  'Boots of Speed',
  'Boots of Levitation',
  'Boots of Traveling and Leaping',
  'Broom of Flying',
  'Spectacles of Reading Magic and Languages',
  'Helm of Telepathy',
  'Helm of Teleportation',
  'Helm of Chaos(Law)',
  'Flying Carpet',
  'Drums of Panic',
  'Horn of Blasting',
  'Gauntlets of Ogre Power',
  'Girdle of Giant Strength',
  'Mirror of Life Trapping',
  'Medallion of Thought Projection',
  'Scarab of Enraging Enemies',
  'Scarab of Insanity',
  'Bag of Tricks',
  'Bean Bag',
  'Bag of Transmuting',
  'Bag of Devouring',
  'Censor of Hostile Air Elementals',
  'Luckstone',
  'Loadstone',
  'Brazier of Sleep Smoke',
  'Bowl of Watery Death',
  'Boots of Dancing',
  'Flask of Curses',
  'Jug of Alchemy',
  'Animated Broom',
  'Decanter of Endless Water',
  'Beaker of Plentiful Potions',
  'Rug of Smothering',
  'Drums of Panic',
  'Drums of Deafness',
  'Horn of Collapsing',
  'Horn of Valhalla',
  'Horn of Bubbles',
  'Gauntlets of Swimming',
  'Gauntlets of Climbing',
  'Gauntlets of Dexterity',
  'Gauntlets of Funbling',
  'Girdle of Sex Change',
  'Necklace of Missiles',
  'Necklace of Strangulation',
  'Oil of Etherialness',
  'Oil of Slipperiness',
  'Lesser Cloak of Protection',
  'Cloak of Protection',
  'Greater Cloak of Protection',
  'Posionous Cloak',
  'Mirror of Mental Prowess',
  'Mirror of Opposition',
  'Trident of Warning',
  'Trident of Commanding Water Creatures',
  'Trident of Submission',
  'Trident of Yearning',
  'Eyes of Charming',
  'Eyes of Petrification',
  'Gem of Brightness',
  'Gem of Seeing',
  'Jewel of Attacks upon the Owner',
  'Lesser Bracers of Defense',
  'Bracers of Defense',
  'Greater Bracers of Defense',
  'Bracers of Defenselessness',
  'Rope of Entanglement',
  'Rope of Climbing',
  'Dust of Appearance',
  'Javelins of Lightning',
  'Arrow of Direction',
  'Wings of Flying',
  'Cube of Force',
  'Protable Hole',
  'Horseshoes of Speed',
  'Sphere of Annihilation',
  'Chime of Opening'
  ],
  trinkets: ["Dog charming whistle",
  "Magic bird call",
  "Animated mouse skeleton",
  "Talking doll",
  "Talking skull - paranoid schizophrenic",
  "Talking skull - bubbly toddler",
  "Hand of Glory",
  "Amulet +1 protection vs Lycanthropes",
  "Amulet +1 protection vs Undead",
  "Amulet of Weather Luck",
  "Butterknife +1",
  "Trowel of Fine Bricklaying",
  "Ashes of a Witch",
  "Dragon's scale",
  "Dust of a mummy",
  "Tiny bottle of green slime",
  "Tanglefoot bag",
  "Glowing stone - bright as torchlight",
  "A single +1 arrow",
  "Blanket of warmth",
  "Umbrella helmet",
  "Horn of Booming Voice",
  "Pocket Fishing Rod",
  "Skull shaped death whistle",
  "Silver dagger",
  "Bottle of Hemlock",
  'Bunch of Wolvesbane',
  'Lunchbox of Freshness',
  'The Animated Kama Sutra',
  'Silver Quill of Inexhaustable Ink',
  'Boots of Loudness',
  'Cloak of Tawdry Brightness',
  'Hat of Rabbits',
  'Clown suit of Creepiness',
  'Necklace of Staining',
  'Chainmail of Excessive Jingliness',
  'Magic Mouth Jewelry Box',
  'Coinpurse of Capacity (small, holds 1000 coins)',
  'Spiked Gauntlets of Itchy Butt',
  'Goggles of Astral Vision',
  'Wand of Flower Summoning',
  'Gauntlets of Ogre Charisma',
  'Crystal Ball of Drawing Unwanted Attention',
  'Amulet of Attracting Livestock',
  'Cloak of Vampire Impersonation',
  'Etherial Shield',
  'Endless ball of string',
  'Mind controllable marble',
  'Amulet of Doppelganger Revelation',
  'Lucky horseshoe',
  'Four leaf clover',
  'Gem of dragon distraction',
  'Charcoal stick of drawing real holes (a passable man sized hole uses a third of it)',
  'Flagon of Drunkenness',
  'Animated statuette',
  'Wand of Firestarting',
  'Mallet of Tenderizing',
  'Socks of Odorlessness',
  'Artistic Imp Box',
  'Coin of Returning',
  "Torn page from a Wizard's Grimoire",
  'Stilts of Striding',
  "Troll's foot (a troll by the next day)",
  "Thimble of quick sewing",
  "Necklace of Accents",
  "Leggings of Embarrassment",
  "Boots of Sleepwalking"
  ],
  armorPowers: [
	"Half encumbrance",
	"Silent movement",
	"Shadow concealment",
	"Climbing",
	"Indestructible",
	"Fire resistance",
	"Cold resistance",
	"Lightning resistance",
	"Regenerate 1 HP per combat round",
	"Shines bright in combat",
	"Wrestling: +2 grappling rolls",
	"Evasion: +2 to saving throws",
	'Can change size',
	'Does not rust or age',
	'Donned by materialization',
	'Cursed'
  ],  
  armor: ["Leather armor",
	  "Scale armor",
	  "Chain mail",
    "Hide armor", 
	  "Plate armor",
	  "Shield",
	  "Helm"
  ],
  weaponPowers: [
	"No encumbrance",
	"Indestructible",
	"Burning Flame on a crit",
	"Chilling Cold on a crit",
	"Stunning Lightning on a crit",
	"Lifestealing: 1 HP each hit",
	"Glows when enemies are close",
	"Shines bright in combat",
	"+2 damage to favored enemy",
	"Flashing parries: +2 AC",
	'Can change size',
	'Does not rust or age',
	'Flies to hand',
	'Cursed'
  ],  
  weapons: ["Battleaxe",
      "Battleaxe",
	  "Battleaxe",
	  "Greataxe",
	  "Greataxe",
	  "Handaxe",
	  "Mace",
	  "Spear",
	  "Handaxe",
	  "Mace",
	  "Spear",
	  "Falx",
	  "Morningstar",
	  "Flail",
	  "Dagger",
	  "Flail",
	  "Dagger",
	  "Dagger",
	  "Dagger",
	  "Seax",
	  "Longbow",
	  "Longbow",
	  "Composite bow",
	  "Short bow",
	  "Short bow",
	  "Sling",
	  "Arrows",
	  "Quiver",
	  "Sling bullets",
	  "Quarrels",
	  "Heavy crossbow",
	  "Light crossbow",
	  "Arrows",
	  "Quiver",
	  "Sling bullets",
	  "Quarrels",
	  "Heavy crossbow",
	  "Light crossbow",
	  "Pick",
	  "Polearm",
	  "Halberd",
	  "Polearm",
	  "Halberd",
	  "Javelin",
	  "Javelin",
	  "Lance",
	  "Pike"
  ],
  hook_items: [ "book",
                "map of all or part of this level",
                "map to deeper level",
                "map to another dungeon",
                "map of part of another dungeon",
                "map showing a secret path",
                "map showing a secret treasure",
                   "map",
                   "note",
                   "note that reveals a bit of the history of the place",
                   "note that reveals a villain's intentions",
                   "journal",
                   "document",
                   "handbill",
                   "symbolic piece of jewelry",
                   "portrait locket",
                   "symbolic item of clothing",
                   "inscription on wall",
                   "mosaic wall",
                   "mosaic floor",
                   "imported trade item",
                   "rare trade goods",
                   "signature weapon",
                   "ceremonial object",
                   "captive",
                   "spirit",
                   "magic mouth",
                   "illusion",
                   "blood trail",
                   "tracks",
                   "scratch marks",
                   "trail of string, bones, teeth, stones, or marks",
                   "chalk mark",
                   "unconscious creature",
                   "spoor from a creature on this level",
                   "spoor from a creature on the level below",
                   "identifiable corpse",
                   "unusual bones or hide",
                   "sound from link or linked area",
                   "breeze",
                   "odor",
                   "light from link or linked area",
                   "lurking dungeon denizen",
                   "talking skull or head",
                   "graffiti"],
  oddities: [
    "A very small door",
	"A pile of corpses",
	"Unquiet spirits",
	"Blinking eyes set into the wall",
	"Holes in the wall",
	"Holes in the floor",
	"Holes in the ceiling",
    "Vermin rush towards the PCs from heaps of refuse",
	"Alcove with a small altar",
	"Rubble",
	"Surprisingly fine furnishings",
    "Bas reliefs",
    "Frescoes",
    "Runes",
    "Creepy statue",
    "Broken statues",
    "Crystal statue",
    "Gaping crevasse across the room",
    "Inscribed floor",
	"A cache of foodstuffs",
	"Water dripping down a wall",
	"A dismembered corpse",
	"Chains anchored to wall",
	"An upward stair that dead-ends",
	"A false door",
	"Strange noises",
	"A child's toy",
	"A small statue",
    "A puzzle",
    "A piece of clothing",
	"Urns",
    "A decapitated head in the center of the room swivels towards the PCs, eyes snapping open and...",
    "A barrel of spare torches",
    "Fountain built on a natural spring",
    "Vermin infested food",
    "Vermin infested bedding",
    "The floor crawls with vermin.",
    "The walls crawl with vermin.",
    "A corpse hangs from a meathook.",
    "A collection of dried ears",
    "An arrangement of stones",
    "A taxidermied creature",
    "A mummified creature",
    "A water drain channel in the floor",
    "Natural crystals",
    "The arm from a statue",
    "The feet of a statue",
    "An instrument of torture",
    "A pyramid of doll heads",
    "A dead monkey in a doll mask",
    "A dead body jams the entrance",
    "A musical instrument",
    "A stick of charcoal",
    "The walls glow faintly",
	"A keg of ale",
	"A bottle of wine",
	"A half eaten meal",
	"Cracks (in walls, ceiling, and/or floor)",
	"The sound of music",
	"Weird moving shadows",
    "Glowing symbols crawl over the walls",
    "Cracks in the floor with an eery glow",
    "A wind rises as PCs enter, blowing the furnishings their way",
    "A dead body starts to float into the air",
    "Uncanny music changes with the mood in the room",
	"Crawling inscriptions on the floor",
	"Ghostly whispers in your ears",
	"A faint, glowing form beckons.",
	"A ghostly scenes plays out and repeats.",
	"Rumbling noise from the walls",
	"Vibrations",
	"Sound is muffled here",
	"Light sources become very dim here.",
    "A body entombed in crystal",
	"Gusts of wind",
	"Vermin stream from a hole in the wall.",
	"The door closes behind with a slam.",
	"A burning brazier",
	"A smoky firepit",
	"Noisome odors",
	"The smell of roasting meat induces hunger.",
	"The smell of baking pie induces hunger.",
	"A keening whine or whistle",
	"Dancing motes of light",
	"Fungus covered corpse",
    "Bones scattered across the floor start to tumble together and assemble...",
	"Shelf fungus",
	"Mushrooms",
	"A gameboard set out to play",
    "A chessboard is set up to play and if the PCs approach, the white king's pawn slides forward two spaces...",
	"A book opened to a page marked with a feather",
	"A glass bell jar with a small creature under it",
	"An undead creature performing a repetitive task",
	"A small golem performing a task",
    "A broken golem pathetically tries to work.",
	"Boxes and crates",
	"A stack of barrels",
	"A ten foot pole leaning in the corner",
	"A rusty sword",
	"A broken helm",
	"A sundered shield",
	"Discarded broken gear",
	"Curious mice",
	"Smoking boots"
	
  ],
  traps:  [ "open pit",
            "falling rocks",
            "door shuts and locks behind",
            "noise alarm trap",
            "concealed pit",
            "spiked pit",
            "scattered caltrops",
            "crossbow trap",
            "spears trap",
            "neck wire",
            "slippery oil trap",
            "leg breaker pit",
            "paint bucket trap",
            "portcullis trap",
            "entanglement trap",
            "deep pit",
            "scything blades",
            "blocking wall",
            "crushing wall",
            "acid trap",
            "poison needle trap",
            "gas trap",
            "illusion wall",
            "invisible wall",
            "illusion concealed trap",
            "concealed bear trap",
            "glue trap",
            "hammer trap",
            "ballista trap",
            "springal trap",
            "spiked door", 
            "swinging spiked beam",
            "cave-in trap",
            "catapult trap",
            "disease trap",
            "smoke trap",
            "fecal spikes trap",
            "electromagnet trap",
            "giant stone ball trap",
            "flame trap",
            "asphyxiation trap",
            "ooze pit trap",
            "slime in a bottle",
            "magical darkness trap",
            "magic immobilization trap",
            "magic elemental trap",
            "magic single target damage trap",
            "magic curse trap",
            "magic monster summoning trap",
            "magic teleport trap",
            "magic obstruction trap",
            "antimagic trap",
            "magic area damage trap",
            "magic antigravity trap",
            "weird magic trap"
            ],
  triggers:[ 
            "weight",
			"stud",
			"shifting flagstone",
            "tripwire",
            "light",
            "noise",
			"fear",
			"odor",
			"timer",
			"a bound spirit",
			"a bound elemental",
			"sound",
            "opening chest",
            "opening door",
            "knob",
			"lever",
            "moving object",
            "air or water movement"
  ],
  disarms: [ 
            "lever",
            "button",
            "key lock",
            "floor plate",
            "stud",
            "concealed lever",
            "disguised lever",
            "disguised knob",
            "a lever hidden in one of the ways in",
            "twist handle",
            "key word",
            "a whistled or sung tune",
            "piling heavy objects on a lever arm",
            "spring",
            "moving object",
            "levers puzzle",
            "statue puzzle",
            "glyphs puzzle",
            "magic puzzle"
  ],
  edgeLabels:[
    "corridor with niches",
	"hallway with inscriptions",
	"corridor",
    "corridor",
    "hallway",
    "broken down door",
    "spiked door",
    "passage blocked by huge corpse",
	"hallway and stairs",
	"corridor with trap",
	"cavern tunnel",
    "blocked tunnel",
    "hastily bricked up wall",
    "collapsed wall",
	"windy tunnel",
    "passage",
    "teleportal",
    "portal",
    "gate",
    "broken gate",
    "broken stair",
    "collapsed bridge",
    "peephole",
    "drain",
	"hallway with trap",
	"corridor",
	"hallway",
    "twisting hallway",
    "hallway",
    "narrow stairs",
    "wide staircase",
    "wide hallway",
    "secret tunnel",
    "long hallway",
    "long tunnel",
	"winding tunnel",
	"tunnel",
	"low ceiling tunnel",
	"ramp",
	"hole in wall",
	"stairs",
	"spiral stairs",
	"ladder",
	"chute",
	"sloping passage",
	"narrow tunnel",
	"narrow hallway", 
	"empty room",
	"a maze of twisty little passages, all different",
    "a maze of twisty little passages, all alike",	
	"secret door",
    "secret door",
    "secret door",
    "secret passage",
	"shifting wall", 
	"revolving wall",
	"vertical shaft",
	"elevator",
    "natural chimney",
	"metal door",
    "chasm ledge path",
    "partial cave-in",
    "ledge",
    "natural ladder",
    "scree slope in cavern",
    "winch over cliff ledge",
    "cavern cliff",
	"jammed door",
	"locked door",
    "channel",
    "hole",
    "mineshaft",
    "overlooks",
    "portcullis",
    "archway",
    "crawlway",
    "window",
    "arches",
    "gateway",
    "rope",
    "mine tunnel",
    "chain",    
    "barred door",
    "vent",
    "hole in the wall",
    "tube",
    "pit",
    "vein",
    "shaft",
    "streambed",
    "boreshaft",
    "duct",
    "barrel vault",
    "arrowslits",
    "breastwork",
    "parapet",
    "stockade",
    "prison bars",
    "palisade",
    "escarpment",
    "murderhole",
    "magic gateway",
    "magic portal",
    "worm tunnel",
    "ventilation shaft",
	"door",
    "sewer",
	"door",
    "door",
    "door",
    "door",
    "door",
    "fortified door",
    "locked door",
    "double doors",
    "magic door"],
	nodeLabels:[
    "Balcony",
    "Room", 
    "Room",
    "Long room", 
    "Room",
    "Room", 
    "Suite of rooms",
    "Mine",
    "Crawlspace",
    "Mine working",
    "Barricaded room",
    "Aquaduct",
    "Barricaded hallway",
    "Fortified cavern",    
    "Midden",
    "Armory",
    "Workroom",
    "Smithy",
    "Stockroom",
    "Ritual chamber",
    "Sanctuary",
    "Fountain",
    "Cistern",
    "Abattoir",
    "Forge",
    "Foundry",
    "Salon",
    "Butchery",
    "Chancel",
    "Sanctum",
    "Place of power",
    "Scriptorium",
    "Library",
    "Chapel",
    "Pantheon",
    "Basilica",
    "Icehouse",
    "Redoubt",
	"Large room", 
	"Small room", 
    "Circular room",
    "Oval room",
    "Hexagonal room",
    "Pentagonal room",
    "Spy nook",
    "Niche",
    "Museum",
    "Gazebo",
    "Lair",
    "Delving",
    "Barrow",
    "Temple",
    "Triangular room",
    "Domed circular room",
    "Barrel vaulted room",
	"A maze of twisty little passages, all different",
    "A maze of twisty little passages, all alike",	
    "Necropolis",
    "Mortuary",
    "Ossuary",
    "Alcove",
    "Antechamber",
    "Apartment",
    "Barracks",
    "Cubicle",
    "Recess",
    "Retreat",
    "Tower",
    "Stall",
    "Hold",
    "Hole",
    "Closet",
    "Cloister",
    "Cavity",
    "Den",
    "Lockup",
    "Charnel house",
    "Boneyard cave",
    "Sepulchre",
    "Garderobe",
    "Dungheap",
    "Nest",
    "Burrow",
    "Crypt",
    "Catacomb",
    "Cell",
    "Cellblock",
    "Compartment",
    "Grave",
    "Grotto",
    "Mausoleum",
    "Tomb",
    "Undercroft",
    "Vault",
    "Cellar",
    "Sewer",
	"Hidden room", 
	"Irregular room",     
	"Cavern",
	"Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Worm tunnel",
    "Lava cave",
    "Foggy cave",
    "Smoke filled room",
    "Irregular hallway",
    "Cave in",
	"Chamber",
    "Chamber",
    "Portico",
    "Grand hall",
    "Vast cavern",
	"Oubliette",
	"Wide corridor",
	"Chamber with pillars",   
	"Chamber with statues",
	"Store room", 
	"Guard room", 
	"Wide hall", 
	"Long hall",
	"Audience chamber", 
	"Shrine", 
	"Fane",
    "Altar",	
	"Chasm",
    "Chasm ledge",
	"Bridged chasm",
	"Bridge across underground river",
	"Underground river ford",
	"Underground riverbank",
	"Laboratory", 
	"Prison", 
	"Treasure chamber",
	"Throne room",
	"Torture chamber",
	"Bedroom",
	"Dais",
	"Landing", 
	"Cave", 
	"Cave with pool"]
	
};

DG.wild = {
  monsters: [
  
  ],
  edgeLabels: [
    "trail",
	"road",
	"high road",
	"low road",
	"ferry",
	"ford",
	"bridge",
	"path",
	"along a stream",
	"along a river",
	"pass",
	"portal",
    "across a bay",
    "across a channel",
    "along an isthmus", 	
	"dirt road",
	"paved road",
	"switchback",
	"down a valley",
	"across a valley",
	"across a river",
	"across a stream"
  ],
  nodeLabels: [
    "Cabin in the woods",
	"Dark forest",
	"Open woods",
	"Meadow",
	"Crag",
	"Mountain",
	"Hills",
	"Citadel",
	"Crossroads",
	"Village",
	"Town",
	"Mine",
	"Monastery",
	"Temple",
	"Valley",
	"Cave",
	"Fortified village",
	"Fortified town",
	"Castle",
	"Hilltop fort",
	"Ruined fort",
	"Ruined castle",
	"City in ruins",
	"Devastated city",
	"Thriving city",
	"Sleepy village",
	"Inn",
	"Way station",
	"Port",
	"Fishing village",
	"Trading fair",
	"Encampment",
	"Grove",
	"Swamp",
	"Marsh",
	"Mudflats",
	"Cliff",
	"Floating mountain",
	"Turtle island",
	"Island",
	"Lake",
	"Pond",
	"Desert",
	"Blasted plain",
	"Plains",
	"Jungle",
	"Forest",
	"Enchanted forest"
  ]
  
}