//This file is the stocking data

DG.stock = {
  monsters: [ 
  [
  "kobold", 
  "goblin", 
  "spider",
  "snake",  
  "rat", 
  "giant rat", 
  "bat", 
  "centipede", 
  "stirge",
  "skeleton",
  "orc",
  "bandit",
  "novice adventurer",
  "weekend cultist",
  "underling"
  ], //level 1
  ["zombie",
  "spirit",
  "ooze",
  "jelly",
  "shadow",
  "dark elf",
  "mutant",
  "crawling hand",
  "man ape",
  "ape man",
  "hobgoblin",
  "lizard",
  "lizard man",
  "berserker",
  "gnoll",
  "giant ant",
  "adventurer",
  "cultist",
  "miserable minion"
  ], //level 2
  ["ghast",
  "giant weasel",
  "bugbear",
  "creeper",
  "snake man",
  "ghoul",
  "gremlin",
  "carrion crawler",
  "rust monster",
  "gelatinous cube",
  "doppelganger",
  "giant spider",
  "night lurker",
  "giant snake",
  "ogre",
  "slime",
  "demonic minion",
  "devil spawn",
  "imp",
  "wight",
  "veteran adventurer",
  "fanatic cultist",
  "evil henchman"], //level 3
  [ "lesser demon",
  "servant devil",
  "cockatrice",
  "serpent priest",
  "lycanthrope",
  "night gaunt",
  "raptor",
  "minotaur",
  "roper",
  "crawling horror",
  "spectre",
  "mold",
  "mimic",
  "troll",
  "hill giant",
  "young dragon",
  "animated statue",
  "wraith",
  "mummy",
  "gargoyle",
  "heroic adventurer",
  "insane cultist",
  "villainous lieutenant"], // level 4
  ["medusa",
  "robot",
  "serpent sorceror",
  "troll lord",
  "horror",
  "manticore",
  "giant",
  "stalker",
  "wyvern",
  "dinosaur",
  "elemental",
  "mental squidman",
  "demon",
  "devil",
  "subadult or adult dragon",
  "ghost",
  "golem",
  "grizzled adventurer",
  "inner circle cultist",
  "villain"], //level 5
  ["hydra",
  "demon lord",
  'elemental prince',
  "devil prince",
  "lich",
  "beholder",
  "wizard",
  "gorgon",
  "chimera",
  "basilisk",
  "vampire",
  "giant worm",
  "old or very old dragon",
  "legendary adventurer",
  "cult leader",
  "evil overlord"] //level 6
  ],
  treasure: [{label: "gold", value: 1},
             {label: "silver", value: 0.1},
             {label: "copper", value: 0.02}, //less actual value if coppers but not such enormous heaps
             {label: "platinum", value: 10},
             {label: "electrum", value: 0.5},
             {label: "x 10 GP gem", value: 10},
             {label: "x 100 GP gem", value: 100},
             {label: "x 200 GP gem", value: 200},
             {label: "x 300 GP gem", value: 300},
             {label: "x 500 GP gem", value: 500},
             {label: "x 1000 GP gem", value: 1000},
             {label: "x 2000 GP gem", value: 2000}//,
             //{label: "jewelry", value: "roll", minValue: 10, maxValue: 10000}
            ],
  magicItems: [ "Healing potion",
                "Strong healing potion",
                "potion",
                "potion",
                "potion",
                "Scroll of spells",
                "Scroll of warding",
                "scroll",
                "trinket",
                "trinket",
                "wand",
                "ring",
                "sword",
                "staff",
                "armor",
                "weapon",
                "book",
                "miscellaneous" ],
  minorMagicItems: [ "Weak healing potion",
                "Healing potion",
                "potion",
                "potion",
                "potion",
				"Scroll with one spell",
                "Scroll with one spell",
                "Scroll of warding",
                "scroll",
                "trinket",
                "trinket" ],
  potions: [ "Giant growth",
             "Shrinking",
			 "Levitation",
			 "Flight",
			 "Fire breath",
			 "Armored skin",
			 "Water breathing",
			 "Restoration",
			 "Cure disease",
			 "Universal antidote",
			 "Antidote to a specific poison",
			 "Delusion",
			 "Lust",
			 "Silence",
			 "Deathlike trance",
			 "Intestinal distress",
			 "Sleeping",
			 "Infatuation",
			 "Polymorph",
			 "Disguise",
			 "Invisibility",
			 "Wall climbing",
			 "Gravity inversion",
			 "Magic suppression",
			 "Inebriation",
			 "Heroism",
			 "Giant strength",
			 "Paranoid Rage",
			 "Animal language",
			 "Speaking any language",
			 "Planar visitation",
			 "Spirit travel",
			 "Treasure finding",
			 "Elemental resistance",
			 "Animal control",
			 "Speed",
			 "Leaping",
			 "Purgation",
			 "Gaseous form",
			 "Weird Mutation",
			 "Spell preparation",
			 "Regeneration"
  ],
  hook_items: [ "book",
                   "map",
                   "note",
                   "journal",
                   "document",
                   "handbill",
                   "symbolic piece of jewelry",
                   "portrait locket",
                   "symbolic item of clothing",
                   "inscription on wall",
                   "mosaic wall",
                   "mosaic floor",
                   "imported trade item",
                   "rare trade goods",
                   "signature weapon",
                   "ceremonial object",
                   "captive",
                   "spirit",
                   "magic mouth",
                   "illusion",
                   "blood trail",
                   "tracks",
                   "scratch marks",
                   "trail of string, bones, teeth, stones, or marks",
                   "chalk mark",
                   "unconscious creature",
                   "spoor from a creature on this level",
                   "spoor from a creature on the level below",
                   "identifiable corpse",
                   "unusual bones or hide",
                   "sound from link or linked area",
                   "breeze",
                   "odor",
                   "light from link or linked area",
                   "lurking dungeon denizen",
                   "talking skull or head",
                   "graffiti"],
  oddities: [
    "a very small door",
	"a pile of corpses",
	"unquiet spirits",
	"blinking eyes set into the wall",
	"holes in the wall",
	"holes in the floor",
	"holes in the ceiling",
	"alcove with a small altar",
	"rubble",
	"surprisingly fine furnishings",
	"a cache of foodstuffs",
	"water dripping down a wall",
	"a dismembered corpse",
	"chains anchored to wall",
	"an upward stair that dead-ends",
	"a false door",
	"strange noises",
	"a child's toy",
	"a small statue",
    "a puzzle",
    "a piece of clothing",
	"urns",
    "a barrel of spare torches",
    "fountain built on a natural spring",
    "vermin infested food",
    "vermin infested bedding",
    "the floor crawls with vermin",
    "the walls crawl with vermin",
    "a corpse hanging from a meathook",
    "a collection of dried ears",
    "an arrangement of stones",
    "a taxidermied craeture",
    "a mummified creature",
    "a water drain channel in the floor",
    "natural crystals",
    "the arm from a statue",
    "the feet of a statue",
    "an instrument of torture",
    "a musical instrument",
    "a stick of charcoal",
    "the walls glow faintly",
	"a keg of ale",
	"a bottle of wine",
	"a half eaten meal",
	"cracks (in walls, ceiling, and/or floor)",
	"the sound of music",
	"weird moving shadows",
	"crawling inscriptions on the floor",
	"ghostly whispers in your ears",
	"a faint, glowing form beckons",
	"a ghostly scenes plays out and repeats",
	"rumbling noise from the walls",
	"vibrations",
	"sound is muffled here",
	"light sources become very dim here",
	"gusts of wind",
	"vermin stream from a hole in the wall",
	"the door closes behind with a slam",
	"a burning brazier",
	"a smoky firepit",
	"noisome odors",
	"the smell of roasting meat induces hunger",
	"the smell of baking pie induces hunger",
	"a keening whine or whistle",
	"dancing motes of light",
	"fungus covered corpse",
	"shelf fungus",
	"mushrooms",
	"a gameboard set out to play",
	"a book opened to a page marked with a feather",
	"a glass bell jar with a small creature under it",
	"an undead creature performing a repetitive task",
	"a small golem performing a task",
	"boxes and crates",
	"a stack of barrels",
	"a ten foot pole leaning in the corner",
	"a rusty sword",
	"a broken helm",
	"a sundered shield",
	"discarded broken gear",
	"curious mice",
	"smoking boots"
	
  ],
  traps:  [ "open pit",
            "falling rocks",
            "door shuts and locks behind",
            "noise alarm trap",
            "concealed pit",
            "spiked pit",
            "scattered caltrops",
            "crossbow trap",
            "spears trap",
            "neck wire",
            "slippery oil trap",
            "leg breaker pit",
            "paint bucket trap",
            "portcullis trap",
            "entanglement trap",
            "deep pit",
            "scything blades",
            "blocking wall",
            "crushing wall",
            "acid trap",
            "poison needle trap",
            "gas trap",
            "illusion wall",
            "invisible wall",
            "illusion concealed trap",
            "concealed bear trap",
            "glue trap",
            "hammer trap",
            "ballista trap",
            "springal trap",
            "spiked door", 
            "swinging spiked beam",
            "cave-in trap",
            "catapult trap",
            "disease trap",
            "smoke trap",
            "fecal spikes trap",
            "electromagnet trap",
            "giant stone ball trap",
            "flame trap",
            "asphyxiation trap",
            "ooze pit trap",
            "slime in a bottle",
            "magical darkness trap",
            "magic immobilization trap",
            "magic elemental trap",
            "magic single target damage trap",
            "magic curse trap",
            "magic monster summoning trap",
            "magic teleport trap",
            "magic obstruction trap",
            "antimagic trap",
            "magic area damage trap",
            "magic antigravity trap",
            "weird magic trap"
            ],
  triggers:[ 
            "weight",
			"stud",
			"shifting flagstone",
            "tripwire",
            "light",
            "noise",
			"fear",
			"odor",
			"timer",
			"a bound spirit",
			"a bound elemental",
			"sound",
            "opening chest",
            "opening door",
            "knob",
			"lever",
            "moving object",
            "air or water movement"
  ],
  disarms: [ 
            "lever",
            "button",
            "key lock",
            "floor plate",
            "stud",
            "concealed lever",
            "disguised lever",
            "disguised knob",
            "twist handle",
            "key word",
            "spring",
            "moving object",
            "levers puzzle",
            "statue puzzle",
            "glyphs puzzle",
            "magic puzzle"
  ],
  edgeLabels:[
    "corridor with niches",
	"hallway with inscriptions",
	"corridor",
    "corridor",
    "hallway",
    "broken down door",
    "spiked door",
    "passage blocked by huge corpse",
	"hallway and stairs",
	"corridor with trap",
	"cavern tunnel",
    "blocked tunnel",
    "hastily bricked up wall",
    "collapsed wall",
	"windy tunnel",
    "passage",
    "teleportal",
    "portal",
    "gate",
    "broken gate",
    "broken stair",
    "collapsed bridge",
    "peephole",
    "drain",
	"hallway with trap",
	"corridor",
	"hallway",
    "hallway",
    "hallway",
    "narrow stairs",
    "wide staircase",
    "wide hallway",
    "secret tunnel",
    "long hallway",
    "long tunnel",
	"winding tunnel",
	"tunnel",
	"low ceiling tunnel",
	"ramp",
	"hole in wall",
	"stairs",
	"spiral stairs",
	"ladder",
	"chute",
	"sloping passage",
	"narrow tunnel",
	"narrow hallway", 
	"empty room",
	"a maze of twisty little passages, all different",
    "a maze of twisty little passages, all alike",	
	"secret door",
    "secret door",
    "secret door",
    "secret passage",
	"shifting wall", 
	"revolving wall",
	"vertical shaft",
	"elevator",
    "natural chimney",
	"metal door",
    "chasm ledge path",
    "partial cave-in",
    "ledge",
    "natural ladder",
    "scree slope in cavern",
    "winch over cliff ledge",
    "cavern cliff",
	"jammed door",
	"locked door",
    "channel",
    "hole",
    "mineshaft",
    "overlooks",
    "portcullis",
    "archway",
    "crawlway",
    "window",
    "arches",
    "gateway",
    "rope",
    "mine tunnel",
    "chain",    
    "barred door",
    "vent",
    "hole in the wall",
    "tube",
    "pit",
    "vein",
    "shaft",
    "streambed",
    "boreshaft",
    "duct",
    "barrel vault",
    "arrowslits",
    "breastwork",
    "parapet",
    "stockade",
    "prison bars",
    "palisade",
    "escarpment",
    "murderhole",
    "magic gateway",
    "magic portal",
    "worm tunnel",
    "ventilation shaft",
	"door",
    "sewer",
	"door",
    "door",
    "door",
    "door",
    "door",
    "fortified door",
    "locked door",
    "double doors",
    "magic door"],
	nodeLabels:[
    "Balcony",
    "Room", 
    "Room",
    "Long room", 
    "Room",
    "Room", 
    "Suite of rooms",
    "Mine",
    "Crawlspace",
    "Mine working",
    "Barricaded room",
    "Aquaduct",
    "Barricaded hallway",
    "Fortified cavern",    
    "Midden",
    "Armory",
    "Workroom",
    "Smithy",
    "Stockroom",
    "Ritual chamber",
    "Sanctuary",
    "Fountain",
    "Cistern",
    "Abattoir",
    "Forge",
    "Foundry",
    "Salon",
    "Butchery",
    "Chancel",
    "Sanctum",
    "Place of power",
    "Scriptorium",
    "Library",
    "Chapel",
    "Pantheon",
    "Basilica",
    "Icehouse",
    "Redoubt",
	"Large room", 
	"Small room", 
    "Circular room",
    "Oval room",
    "Hexagonal room",
    "Pentagonal room",
    "Spy nook",
    "Niche",
    "Museum",
    "Gazebo",
    "Lair",
    "Delving",
    "Barrow",
    "Temple",
    "Triangular room",
    "Domed circular room",
    "Barrel vaulted room",
	"A maze of twisty little passages, all different",
    "A maze of twisty little passages, all alike",	
    "Necropolis",
    "Mortuary",
    "Ossuary",
    "Alcove",
    "Antechamber",
    "Apartment",
    "Barracks",
    "Cubicle",
    "Recess",
    "Retreat",
    "Tower",
    "Stall",
    "Hold",
    "Hole",
    "Closet",
    "Cloister",
    "Cavity",
    "Den",
    "Lockup",
    "Charnel house",
    "Boneyard cave",
    "Sepulchre",
    "Garderobe",
    "Dungheap",
    "Nest",
    "Burrow",
    "Crypt",
    "Catacomb",
    "Cell",
    "Cellblock",
    "Compartment",
    "Grave",
    "Grotto",
    "Mausoleum",
    "Tomb",
    "Undercroft",
    "Vault",
    "Cellar",
    "Sewer",
	"Hidden room", 
	"Irregular room",     
	"Cavern",
	"Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Intersection",
    "Worm tunnel",
    "Lava cave",
    "Foggy cave",
    "Smoke filled room",
    "Irregular hallway",
    "Cave in",
	"Chamber",
    "Chamber",
    "Portico",
    "Grand hall",
    "Vast cavern",
	"Oubliette",
	"Wide corridor",
	"Chamber with pillars",   
	"Chamber with statues",
	"Store room", 
	"Guard room", 
	"Wide hall", 
	"Long hall",
	"Audience chamber", 
	"Shrine", 
	"Fane",
    "Altar",	
	"Chasm",
    "Chasm ledge",
	"Bridged chasm",
	"Bridge across underground river",
	"Underground river ford",
	"Underground riverbank",
	"Laboratory", 
	"Prison", 
	"Treasure chamber",
	"Throne room",
	"Torture chamber",
	"Bedroom",
	"Dais",
	"Landing", 
	"Cave", 
	"Cave with pool"]
	
};

DG.wild = {
  monsters: [
  
  ],
  edgeLabels: [
    "trail",
	"road",
	"high road",
	"low road",
	"ferry",
	"ford",
	"bridge",
	"path",
	"along a stream",
	"along a river",
	"over a pass",
	"dirt road",
	"paved road",
	"switchback",
	"across a valley",
	"across a river",
	"across a stream"
  ],
  nodeLabels: [
    "Cabin in the woods",
	"Dark forest",
	"Open woods",
	"Meadow",
	"Crag",
	"Mountain",
	"Hills",
	"Citadel",
	"Crossroads",
	"Village",
	"Town",
	"Mine",
	"Monastery",
	"Temple",
	"Valley",
	"Cave",
	"Fortified village",
	"Fortified town",
	"Castle",
	"Hilltop fort",
	"Ruined fort",
	"Ruined castle",
	"City in ruins",
	"Devastated city",
	"Thriving city",
	"Sleepy village",
	"Inn",
	"Way station",
	"Port",
	"Fishing village",
	"Trading fair",
	"Encampment",
	"Grove",
	"Swamp",
	"Marsh",
	"Mudflats",
	"Cliff",
	"Floating mountain",
	"Turtle island",
	"Island",
	"Lake",
	"Pond",
	"Desert",
	"Blasted plain",
	"Plains",
	"Jungle",
	"Forest",
	"Enchanted forest"
  ]
  
}